const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const root=require('path').resolve(__dirname,'..')+require('path').sep;
const ts=require(root+'node_modules/typescript');
const source=ts.transpileModule(fs.readFileSync(root+'app/api/ledger/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
async function harness(role='admin'){
 const store=new Map([['members/actor',{id:'actor',role,name:'Actor',email:'actor@example.com',joinedAt:'2026-10-01'}],['members/member',{id:'member',role:'member',joinedAt:'2026-10-01'}]]);let serial=0;
 const ref=(collection,id)=>({id,path:collection+'/'+id,get:async()=>snap(collection+'/'+id)});
 const snap=path=>({exists:store.has(path),data:()=>structuredClone(store.get(path))});
 const db={collection:name=>({where:(field,op,value)=>({get:async()=>({docs:[...store].filter(([k,v])=>k.startsWith(name+'/')&&v[field]===value).map(([k,v])=>({id:k.split('/')[1],data:()=>structuredClone(v)}))})}),doc:id=>ref(name,id||'auto-'+(++serial)),get:async()=>({docs:[...store].filter(([k])=>k.startsWith(name+'/')).map(([k,v])=>({id:k.split('/')[1],data:()=>structuredClone(v)}))})}),runTransaction:async fn=>{const writes=[];const result=await fn({get:async r=>snap(r.path),set:(r,v)=>writes.push(()=>store.set(r.path,structuredClone(v))),delete:r=>writes.push(()=>store.delete(r.path))});writes.forEach(w=>w());return result;}};
 const calculation=await import(require('url').pathToFileURL(root+'lib/calculation.mjs').href);
 const mockRequire=name=>name==='next/server'?{NextResponse:{json:(body,init={})=>({status:init.status||200,body})}}:name==='@/lib/admin'?{db:()=>db,adminAuth:()=>({verifyIdToken:async()=>({uid:'actor',email_verified:true})})}:name==='@/lib/calculation.mjs'?calculation:require(name);
 const module={exports:{}};vm.runInNewContext('(function(require,module,exports){'+source+'\n})',{console,process,Object,Date})(mockRequire,module,module.exports);
 const post=(action,payload)=>module.exports.POST({headers:{get:()=> 'Bearer token'},json:async()=>({action,payload})});
 const get=()=>module.exports.GET({headers:{get:()=> 'Bearer token'},nextUrl:{searchParams:{get:()=> '2026-10'}}});return {store,post,get};
}
test('editing expense preserves original author and does not duplicate',async()=>{const {store,post}=await harness();store.set('expenses/e1',{date:'2026-10-01',amount:300,category:'food',title:'Market',createdBy:'original'});const result=await post('expense',{id:'e1',date:'2026-10-02',amount:450,category:'gas',title:'Gas'});assert.equal(result.status,200);assert.equal(store.get('expenses/e1').amount,450);assert.equal(store.get('expenses/e1').createdBy,'original');assert.equal([...store.keys()].filter(k=>k.startsWith('expenses/')).length,1);assert.ok([...store].some(([k,v])=>k.startsWith('audit/')&&v.action==='edit'&&v.before.amount===300));});
test('editing deposit replaces old amount',async()=>{const {store,post}=await harness();store.set('deposits/d1',{memberId:'member',date:'2026-10-01',amount:2000,note:''});const result=await post('deposit',{id:'d1',memberId:'member',date:'2026-10-02',amount:2500,note:'Corrected'});assert.equal(result.status,200);assert.equal(store.get('deposits/d1').amount,2500);assert.equal([...store.keys()].filter(k=>k.startsWith('deposits/')).length,1);});
test('meal date change moves entry; conflicting date remains untouched',async()=>{const {store,post}=await harness();const meal={memberId:'member',date:'2026-10-01',breakfast:1,lunch:1,dinner:1};store.set('meals/member_2026-10-01',meal);let result=await post('meal',{...meal,id:'member_2026-10-01',date:'2026-10-02'});assert.equal(result.status,200);assert.equal(store.has('meals/member_2026-10-01'),false);store.set('meals/member_2026-10-03',{...meal,date:'2026-10-03'});result=await post('meal',{...meal,id:'member_2026-10-02',date:'2026-10-03',lunch:0});assert.equal(result.status,400);assert.equal(store.get('meals/member_2026-10-03').lunch,1);assert.equal(store.has('meals/member_2026-10-02'),true);});
test('delete archives original entry with actor and removes it from active ledger',async()=>{const {store,post}=await harness();store.set('expenses/e1',{amount:300,title:'Market'});const result=await post('delete',{kind:'expense',id:'e1'});assert.equal(result.status,200);assert.equal(store.has('expenses/e1'),false);assert.ok([...store].some(([k,v])=>k.startsWith('deletedEntries/')&&v.record.amount===300&&v.deletedBy==='actor'));});
test('member cannot edit or delete ledger entries',async()=>{const {store,post}=await harness('member');store.set('expenses/e1',{amount:300});for(const action of ['expense','delete'])assert.equal((await post(action,{kind:'expense',id:'e1'})).status,403);assert.equal(store.get('expenses/e1').amount,300);});
test('missing edit and unsafe delete targets cannot create or remove records',async()=>{const {store,post}=await harness();assert.equal((await post('expense',{id:'missing',date:'2026-10-01',amount:300,category:'food',title:'Test'})).status,400);assert.equal(store.has('expenses/missing'),false);assert.equal((await post('delete',{kind:'members',id:'actor'})).status,400);assert.equal((await post('delete',{kind:'expense',id:'a/b'})).status,400);assert.equal(store.has('members/actor'),true);});

const future=()=>new Date(Date.now()+86400000).toISOString().slice(0,10);
test('pending account receives no ledger and cannot create meals or requests',async()=>{const {store,post,get}=await harness('member');store.get('members/actor').status='pending';store.get('members/actor').periods=[];store.set('deposits/private',{memberId:'member',date:'2026-10-01',amount:500});const response=await get();assert.equal(response.status,200);assert.equal(response.body.deposits.length,0);assert.equal(response.body.members.length,1);assert.equal((await post('requestMeal',{date:future(),breakfast:1,lunch:1,dinner:0})).status,400);assert.equal((await post('meal',{memberId:'actor',date:future(),breakfast:1,lunch:1,dinner:0})).status,400);});
test('member can rename self but cannot approve membership or change another member',async()=>{const {store,post}=await harness('member');assert.equal((await post('profile',{name:'New Name',memberId:'member',status:'active'})).status,200);assert.equal(store.get('members/actor').name,'New Name');assert.notEqual(store.get('members/member').name,'New Name');assert.equal((await post('memberUpdate',{memberId:'member',status:'active'})).status,403);});
test('admin approves pending member and removal retains ledger with end date',async()=>{const {store,post}=await harness();store.set('members/new',{id:'new',name:'New',role:'member',joinedAt:'2026-01-01',status:'pending',periods:[]});assert.equal((await post('memberUpdate',{memberId:'new',status:'active'})).status,200);assert.equal(store.get('members/new').periods.length,1);store.set('deposits/d1',{memberId:'new',date:'2026-10-01',amount:100});assert.equal((await post('memberUpdate',{memberId:'new',status:'deleted'})).status,200);assert.equal(store.has('members/new'),true);assert.equal(store.get('members/new').status,'deleted');assert.ok(store.get('members/new').periods[0].end);assert.equal(store.has('deposits/d1'),true);assert.equal((await post('memberUpdate',{memberId:'actor',status:'deleted'})).status,403);});
test('manager cannot change membership and admin cannot remove another admin',async()=>{let h=await harness('manager');assert.equal((await h.post('memberUpdate',{memberId:'member',status:'active'})).status,403);h=await harness();h.store.get('members/member').role='admin';assert.equal((await h.post('memberUpdate',{memberId:'member',status:'deleted'})).status,403);});
test('meal request cannot impersonate another member or affect ledger before approval',async()=>{const {store,post,get}=await harness('member');const date=future();assert.equal((await post('requestMeal',{memberId:'member',date,breakfast:1,lunch:1,dinner:0})).status,200);assert.equal(store.get('mealRequests/actor_'+date).memberId,'actor');assert.equal([...store.keys()].filter(k=>k.startsWith('meals/')).length,0);const response=await get();assert.equal(response.body.requests.length,1);assert.equal((await post('reviewRequest',{id:'actor_'+date,status:'approved'})).status,403);});
test('approval writes one daily meal atomically and duplicate review is rejected',async()=>{const {store,post}=await harness();const date=future();store.set('mealRequests/r',{memberId:'member',date,breakfast:1,lunch:0,dinner:1,status:'pending',baseline:'none'});assert.equal((await post('reviewRequest',{id:'r',status:'approved'})).status,200);assert.equal(store.get('meals/member_'+date).dinner,1);assert.equal(store.get('mealRequests/r').status,'approved');assert.equal((await post('reviewRequest',{id:'r',status:'approved'})).status,400);assert.equal([...store.keys()].filter(k=>k.startsWith('meals/')).length,1);});
test('changed daily meal or excluded member cannot be overwritten by approval',async()=>{const {store,post}=await harness();const date=future();store.set('mealRequests/r',{memberId:'member',date,breakfast:1,lunch:0,dinner:1,status:'pending',baseline:'none'});store.set('meals/member_'+date,{breakfast:0,lunch:1,dinner:0});assert.equal((await post('reviewRequest',{id:'r',status:'approved'})).status,400);assert.equal(store.get('meals/member_'+date).lunch,1);assert.equal(store.get('mealRequests/r').status,'pending');store.delete('meals/member_'+date);store.get('members/member').status='excluded';assert.equal((await post('reviewRequest',{id:'r',status:'approved'})).status,400);assert.equal(store.has('meals/member_'+date),false);});
test('member can cancel only own pending request; past dates and invalid quantities are rejected',async()=>{const {store,post}=await harness('member');store.set('mealRequests/other',{memberId:'member',status:'pending'});assert.equal((await post('cancelRequest',{id:'other'})).status,403);const date=future();assert.equal((await post('requestMeal',{date:'2020-01-01',breakfast:1,lunch:1,dinner:1})).status,400);assert.equal((await post('requestMeal',{date,breakfast:-1,lunch:1,dinner:1})).status,400);await post('requestMeal',{date,breakfast:0,lunch:1,dinner:0});assert.equal((await post('cancelRequest',{id:'actor_'+date})).status,200);assert.equal(store.get('mealRequests/actor_'+date).status,'cancelled');});

test('first verified login creates a pending account rather than active membership',async()=>{const {store,get}=await harness('member');store.delete('members/actor');const result=await get();assert.equal(result.status,200);assert.equal(store.get('members/actor').status,'pending');assert.deepEqual(store.get('members/actor').periods,[]);assert.equal(result.body.summary.statements.length,0);});
test('approval cannot make pre-membership backdated entries',async()=>{const {store,post}=await harness();store.get('members/member').periods=[{start:'2026-11-01'}];assert.equal((await post('deposit',{memberId:'member',date:'2026-10-01',amount:200,note:''})).status,400);});
test('rejected request does not change existing ledger and can be resubmitted',async()=>{const {store,post}=await harness('member');const date=future();await post('requestMeal',{date,breakfast:1,lunch:0,dinner:0});store.get('members/actor').role='manager';assert.equal((await post('reviewRequest',{id:'actor_'+date,status:'rejected'})).status,200);assert.equal(store.has('meals/actor_'+date),false);store.get('members/actor').role='member';assert.equal((await post('requestMeal',{date,breakfast:0,lunch:1,dinner:0})).status,200);assert.equal(store.get('mealRequests/actor_'+date).status,'pending');});

test('daily sheet saves multiple members together and edits replace rather than add',async()=>{const {store,post}=await harness();const date='2026-10-06';const old={memberId:'member',date,breakfast:1,lunch:1,dinner:0};store.set('meals/member_'+date,old);store.set('meals/member_2026-10-05',{...old,date:'2026-10-05'});let result=await post('mealsBulk',{date,entries:[{memberId:'actor',breakfast:0.5,lunch:1,dinner:1,baseline:'none'},{memberId:'member',breakfast:0,lunch:0.5,dinner:1,baseline:'[1,1,0]'}]});assert.equal(result.status,200);assert.equal(result.body.saved,2);assert.equal(store.get('meals/actor_'+date).breakfast,0.5);assert.equal(store.get('meals/member_'+date).lunch,0.5);assert.equal(store.get('meals/member_2026-10-05').lunch,1);result=await post('mealsBulk',{date,entries:[{memberId:'actor',breakfast:1,lunch:0,dinner:0,baseline:'[0.5,1,1]'}]});assert.equal(result.status,200);assert.equal(store.get('meals/actor_'+date).breakfast,1);assert.equal([...store.keys()].filter(k=>k.startsWith('meals/actor_')).length,1);assert.ok([...store].some(([k,v])=>k.startsWith('audit/')&&v.source==='daily-sheet'&&v.action==='edit'));});
test('stale daily sheet fails atomically without overwriting new approval or other members',async()=>{const {store,post}=await harness();const date='2026-10-06';store.set('meals/member_'+date,{memberId:'member',date,breakfast:1,lunch:1,dinner:1});const result=await post('mealsBulk',{date,entries:[{memberId:'actor',breakfast:1,lunch:1,dinner:1,baseline:'none'},{memberId:'member',breakfast:0,lunch:0,dinner:0,baseline:'none'}]});assert.equal(result.status,400);assert.equal(store.has('meals/actor_'+date),false);assert.equal(store.get('meals/member_'+date).lunch,1);assert.equal([...store.keys()].filter(k=>k.startsWith('audit/')).length,0);});
test('daily sheet rejects duplicate targets, invalid dates, quarters, empty values and oversized payloads',async()=>{const {store,post}=await harness();const entry={memberId:'member',breakfast:0.5,lunch:1,dinner:1,baseline:'none'};for(const payload of [{date:'2026-02-30',entries:[entry]},{date:'2026-10-06',entries:[entry,entry]},{date:'2026-10-06',entries:[{...entry,breakfast:0.25}]},{date:'2026-10-06',entries:[{...entry,lunch:null}]},{date:'2026-10-06',entries:[{...entry,memberId:'a/b'}]},{date:'2026-10-06',entries:[]},{date:'2026-10-06',entries:Array(201).fill(entry)}])assert.equal((await post('mealsBulk',payload)).status,400);assert.equal([...store.keys()].filter(k=>k.startsWith('meals/')).length,0);});
test('member cannot bulk write and inactive or ineligible targets stop entire save',async()=>{let h=await harness('member');const date='2026-10-06',entry={memberId:'member',breakfast:1,lunch:1,dinner:1,baseline:'none'};assert.equal((await h.post('mealsBulk',{date,entries:[entry]})).status,403);for(const status of ['pending','excluded','deleted']){h=await harness();h.store.get('members/member').status=status;assert.equal((await h.post('mealsBulk',{date,entries:[{...entry,memberId:'actor'},entry]})).status,400);assert.equal(h.store.has('meals/actor_'+date),false);}h=await harness();h.store.get('members/member').periods=[{start:'2026-11-01'}];assert.equal((await h.post('mealsBulk',{date,entries:[entry]})).status,400);});
