const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const root=require('path').resolve(__dirname,'..')+require('path').sep;
const ts=require(root+'node_modules/typescript');
const source=ts.transpileModule(fs.readFileSync(root+'app/api/ledger/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
async function harness(role='admin'){
 const store=new Map([['members/actor',{id:'actor',role,name:'Actor',email:'actor@example.com',joinedAt:'2026-10-01'}],['members/member',{id:'member',role:'member',joinedAt:'2026-10-01'}]]);let serial=0;
 const ref=(collection,id)=>({id,path:collection+'/'+id,get:async()=>snap(collection+'/'+id)});
 const snap=path=>({exists:store.has(path),data:()=>structuredClone(store.get(path))});
 const db={collection:name=>({doc:id=>ref(name,id||'auto-'+(++serial)),get:async()=>({docs:[...store].filter(([k])=>k.startsWith(name+'/')).map(([k,v])=>({id:k.split('/')[1],data:()=>structuredClone(v)}))})}),runTransaction:async fn=>{const writes=[];const result=await fn({get:async r=>snap(r.path),set:(r,v)=>writes.push(()=>store.set(r.path,structuredClone(v))),delete:r=>writes.push(()=>store.delete(r.path))});writes.forEach(w=>w());return result;}};
 const calculation=await import(require('url').pathToFileURL(root+'lib/calculation.mjs').href);
 const mockRequire=name=>name==='next/server'?{NextResponse:{json:(body,init={})=>({status:init.status||200,body})}}:name==='@/lib/admin'?{db:()=>db,adminAuth:()=>({verifyIdToken:async()=>({uid:'actor',email_verified:true})})}:name==='@/lib/calculation.mjs'?calculation:require(name);
 const module={exports:{}};vm.runInNewContext('(function(require,module,exports){'+source+'\n})',{console,process,Object,Date})(mockRequire,module,module.exports);
 const post=(action,payload)=>module.exports.POST({headers:{get:()=> 'Bearer token'},json:async()=>({action,payload})});
 return {store,post};
}
test('editing expense preserves original author and does not duplicate',async()=>{const {store,post}=await harness();store.set('expenses/e1',{date:'2026-10-01',amount:300,category:'food',title:'Market',createdBy:'original'});const result=await post('expense',{id:'e1',date:'2026-10-02',amount:450,category:'gas',title:'Gas'});assert.equal(result.status,200);assert.equal(store.get('expenses/e1').amount,450);assert.equal(store.get('expenses/e1').createdBy,'original');assert.equal([...store.keys()].filter(k=>k.startsWith('expenses/')).length,1);assert.ok([...store].some(([k,v])=>k.startsWith('audit/')&&v.action==='edit'&&v.before.amount===300));});
test('editing deposit replaces old amount',async()=>{const {store,post}=await harness();store.set('deposits/d1',{memberId:'member',date:'2026-10-01',amount:2000,note:''});const result=await post('deposit',{id:'d1',memberId:'member',date:'2026-10-02',amount:2500,note:'Corrected'});assert.equal(result.status,200);assert.equal(store.get('deposits/d1').amount,2500);assert.equal([...store.keys()].filter(k=>k.startsWith('deposits/')).length,1);});
test('meal date change moves entry; conflicting date remains untouched',async()=>{const {store,post}=await harness();const meal={memberId:'member',date:'2026-10-01',breakfast:1,lunch:1,dinner:1};store.set('meals/member_2026-10-01',meal);let result=await post('meal',{...meal,id:'member_2026-10-01',date:'2026-10-02'});assert.equal(result.status,200);assert.equal(store.has('meals/member_2026-10-01'),false);store.set('meals/member_2026-10-03',{...meal,date:'2026-10-03'});result=await post('meal',{...meal,id:'member_2026-10-02',date:'2026-10-03',lunch:0});assert.equal(result.status,400);assert.equal(store.get('meals/member_2026-10-03').lunch,1);assert.equal(store.has('meals/member_2026-10-02'),true);});
test('delete archives original entry with actor and removes it from active ledger',async()=>{const {store,post}=await harness();store.set('expenses/e1',{amount:300,title:'Market'});const result=await post('delete',{kind:'expense',id:'e1'});assert.equal(result.status,200);assert.equal(store.has('expenses/e1'),false);assert.ok([...store].some(([k,v])=>k.startsWith('deletedEntries/')&&v.record.amount===300&&v.deletedBy==='actor'));});
test('member cannot edit or delete ledger entries',async()=>{const {store,post}=await harness('member');store.set('expenses/e1',{amount:300});for(const action of ['expense','delete'])assert.equal((await post(action,{kind:'expense',id:'e1'})).status,403);assert.equal(store.get('expenses/e1').amount,300);});
test('missing edit and unsafe delete targets cannot create or remove records',async()=>{const {store,post}=await harness();assert.equal((await post('expense',{id:'missing',date:'2026-10-01',amount:300,category:'food',title:'Test'})).status,400);assert.equal(store.has('expenses/missing'),false);assert.equal((await post('delete',{kind:'members',id:'actor'})).status,400);assert.equal((await post('delete',{kind:'expense',id:'a/b'})).status,400);assert.equal(store.has('members/actor'),true);});
